🧑‍💻 pre-commit now runs unit tests

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -5,6 +5,7 @@ GREEN="\033[1;32m"
 COLOR_RESET="\033[0m"
 
 linter_exit_code=1
+tests_exit_code=1
 staged_files=$(git diff --cached --diff-filter=d --name-only | grep -E '.js$|.vue$') # grab only .js or .vue files
 
 # Run prettier
@@ -17,9 +18,21 @@ echo "\n Linting files with ESLint: \n"
 
 linter_exit_code=$?
 
+# Run unit tests
+npm run unit -- --silent
+tests_exit_code=$?
+
 if [ ! -z "$staged_files" ]
 then
     git add -f $staged_files
+fi
+
+if [ $tests_exit_code -ne 0 ]
+then
+  echo "\n${RED} ❌ Unit test suite failed :(${COLOR_RESET}\n"
+  exit 1
+else
+  echo "\n${GREEN} ✔ Unit test suite passed successfully :)${COLOR_RESET}\n"
 fi
 
 if [ $linter_exit_code -ne 0 ]
